### ISSUE TITLE
Buglar

### ISSUE THREAD

**Issue by Splaj** [scaber/TurkSeker#2]
Tüm veriler tablosundan id sütunu kaldırılacak.sol üstteki türkşeker logosuna basınca index3 sayfasına gitmeye calısıp hata veriyor.ana sayfa ve tüm veriler tablosunda soldaki menüyü kapatınca tablo kayıyor. user adminrole e sahip kullanıcı login olamıyor.giriş sayfasına emaf ve türk seker logoları olan navbar eklenecek.

**Comment by Splaj** [comment]
Tablolarda 3 basamaktan sonrasını göstermeyecek. tablolarda sutün aralıkları veri uzunluğuna göre ayarlanacak.

**Comment by Splaj** [comment]
Kullanıcı adı şifre yazmadan giriş yap a basılırsa tablo ya gönderip hata veriyor

**Comment by tayfunkilic** [comment]
> Tüm veriler tablosundan id sütunu kaldırılacak.sol üstteki türkşeker logosuna basınca index3 sayfasına gitmeye calısıp hata veriyor.ana sayfa ve tüm veriler tablosunda soldaki menüyü kapatınca tablo kayıyor. user adminrole e sahip kullanıcı login olamıyor.giriş sayfasına emaf ve türk seker logoları olan navbar eklenecek.



> user adminrole e sahip kullanıcı login olamıyor.giriş sayfasına emaf ve türk seker logoları olan navbar eklenecek.

user adminrole e sahip kullanıcı login olamıyor.giriş sayfasına emaf ve türk seker logoları olan navbar eklenecek. hariç düzelttim

**Comment by tayfunkilic** [comment]
> Kullanıcı adı şifre yazmadan giriş yap a basılırsa tablo ya gönderip hata veriyor

Düzelttim
